version: '3.7'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: shop
      DB_USERNAME: butterfly
      DB_PASSWORD: root
    ports:
      - "8000:8000"
    volumes:
      - './api:/app/api'
      - '/app/api/vendor'
    networks:
      - app
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    tty: true
    ports:
      - '3000:3000'
    environment:
      # track file changes for Windows devices
      - WATCHPACK_POLLING=true
    volumes:
      - './client:/app/client'
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: butterfly
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

volumes:
  db-data: ~

networks:
  app:
    driver: bridge